services:
  ros-manipulator:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: alvarobajceps/ros-manipulator:latest
    container_name: ros-manipulator
    hostname: ros-manipulator
    network_mode: "host"
    init: true
    environment:
      - TZ=Europe/Warsaw
      - ROS_ENABLE_AUTOSTART=1
      - ROS_BUILD_ON_STARTUP=on-failure
    volumes:
      - type: bind
        source: ./
        target: /mnt/local
        bind:
          create_host_path: true
      - type: bind
        source: ./.devcontainer/rex
        target: /etc/init.d/rex
        bind:
          create_host_path: true
    restart: unless-stopped
